### PR TITLE
Fix issue with calling removed legacy function

### LINKED ISSUE #147: ERRROR compiling example SimpleOnButton
Compiling your simple example I receive this error

c:\Arduino2\libraries\OneButton\src\OneButton.cpp: In constructor 'OneButton::OneButton(int, bool, bool)':
c:\Arduino2\libraries\OneButton\src\OneButton.cpp:33:7: error: too many arguments to function 'void init()'
   33 |   init(pin, pullupActive ? INPUT_PULLUP : INPUT, activeLow);
      |   ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from c:\Arduino2\libraries\OneButton\src\OneButton.h:28,
                 from c:\Arduino2\libraries\OneButton\src\OneButton.cpp:19:

### PR DESCRIPTION
**Pull request by thebentern**
Fixes #147

Hi from the Meshtastic project 👋 😄

### CODE REVIEW

**Comment by dsagdfgsFD** [comment]
Fixed it for me! Thanks.

**Comment by geeksville** [comment]
hi @mathertel I think there might still be a small problem:

The release name at https://github.com/mathertel/OneButton/releases is not "2.6.1" but instead "fixing compilation issue ...".  This breaks the github 'release' resolution that platformio uses to find releases (it only sees 2.6.0 as the latest release).  For instance look what github says is the latest release on https://github.com/mathertel/OneButton.

Awesome project btw.

cc @thebentern

**Comment by mathertel** [comment]
Renamed. So it should work now hopefully

/ Matthias Hertel
________________________________

**Comment by jp-bennett** [comment]
@mathertel may need to mark 2.6.1 as latest, too.

**Pull request merged**
