### PR TITLE
added tripple click event

### PR DESCRIPTION
**Pull request by Blaubart**

### CODE REVIEW

**Comment by mathertel** [comment]
Why don't you use multiclick ?
1,2,3,... Where to stop having explicit functions ?

**Comment by Blaubart** [comment]
Because I need 4 options. I think it is reasonable to have 4 options.

**Comment by mathertel** [comment]
the use multi-click and test the number of clicks using the getNumberClicks().
I think that this is acceptable and will support your requirement and still the library is small enough for all processors.
So no merge.

**Comment by Blaubart** [comment]
OK, thats OK, but I didn't know about getNumberClicks (). It is not described in Readme.

**Pull request closed without merging**
