### PR TITLE
Optimization and new function for multiple clicks

### PR DESCRIPTION
**Pull request by ShaggyDog18**
Optimized the Time Machine code and introduced new functions for multiple clicks:
  trippleClickFunc() for multiple 3 and more clicks; 
  getNumberClicks() to return number of clicks;

Introduced #define PARAM_FUNC - if commented in oneButton.h , call functions with parameters will not be used to save space;

Modified SimpleOneButton example to test more OneButton functions including new trippleClickFunc() and getNumberClicks() functions.

### CODE REVIEW

**Comment by mathertel** [comment]
There are many improvements I like to take into the library. Your changes are just too much in one pull request.
For now I created branch 'Improvements_59' and take over some lines from your work and your commitment.

**Comment by ShaggyDog18** [comment]
Hi Matthias,

I treated your development carefully and made step-by-step improvements.
You may track them in my multiple intermediate commits.
I am grateful for your initial design and now I use the optimized library
in all my projects.
My optimized version is working fine and reliably. So, you may just accept
it as a whole and benefit from my efforts and contribution!
Anyway, that's your decision and I will be glad if you accept any of my
improvements...

Cheers,
Sergiy

**Comment by mathertel** [comment]
Hi

thank you for your contributions. I studied your commits and there are several thing I really liked and took over to version 2.0.
I just like to comment because I also made some improvements just influenced by existing pull requests.

There is a huge difference between pull requests that do fix things and change just a few lines. I normally accept them quickly.
But there are also pull requests that change a lot - and that's hard to handle.
Especially the expectation from myself is to prove and test to keep the library in a good condition and that takes time as well.

Now time has come to do some fundamental changes for improvements but also push back to keep size small.

* To use an enum for the state indeed increases readability and the big switch statement even reduces the library size.

* Thanks for all the text in readme file. This is great work !
  I then created a CHANGELOG to keep change hints and library documentation apart.

* You introduced the TripleClick but I preferred the idea of mitchsf of implementing the multiClick also similar to the pull request #27 from aslobodyanuk.

* The multi-click approach I liked a lot and I added this feature by re-arranging some state things.
  You can find the updated state diagram in the article at  http://www.mathertel.de/Arduino/OneButtonLibrary.aspx
  I kept the signatures from the doubleClick functions so the number of clicks is not passed as a parameter but you can get it.

* I also use ESP8266 boards so I added some reasonable pin definitions in the examples and checked the examples.

* I included the changes to the default timings for click and press times (now 400/800, was 600/1000) I found reasonable.

* I kept the int datatype where a specific length is not strictly required assuming 16-bit minimum is given.
  This is common to the ARDUINO programming style.

Thanks again. There is some docu to do and then I will publish version 2.0.0.

**Comment by ShaggyDog18** [comment]
Thank you, Matthias!

let me stress that my tripleClick is essentially deployment of a
multiClick!  Agree that "multiClick" name fits better to the method! I will
rename it in my branch
TripleClick works as a multiclick function, you can click on and on up to
dozen clicks and more... Try SampleBotton example and try multi clicks as
much as you'd have patience. I clicked once for about 50 clicks :-)

Right, my main goal was to make the library as compact as possible, so that
it fits applications for uControllers with scarce resources...

Looking forward to your coming Rel 2.

Cheers,
Sergiy

**Pull request closed without merging**
