### PR TITLE
Add cppcheck

### PR DESCRIPTION
**Pull request by mkinney**
See https://github.com/danmar/cppcheck/ or https://cppcheck.sourceforge.io/ for more info about cppcheck

~~and for the github action:~~

~~https://github.com/marketplace/actions/cppcheck-action~~

I excluded the "knownConditionTrueFalse" in the suppressions.txt file. May want to look into that.

### CODE REVIEW

**Comment by mkinney** [comment]
I have not tested that github action, so it make take some tweaking.

**Comment by mkinney** [comment]
I was able to test the github action on my repo.

Let me know if you have any questions/suggestions/comments.

**Comment by mathertel** [comment]
Looks interesting.
When you have finished the settings I will merge.

(Already saw one of your the results ([knownConditionTrueFalse])
This is usually removed by the optimizing compiler so is not in effect but surely can be cleaned up.

**Comment by mkinney** [comment]
I’m finished with it, so please merge if ok.

I would be grateful if the knownConditionTrueFalse could be fixed at some point.

thanks

**Pull request merged**
